# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iofogctl < Formula
  desc "CLI for iofog"
  homepage "https://github.com/eclipse-iofog/iofogctl"
  version "3.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.0.6/iofogctl_3.0.6_macos_amd64.tar.gz"
      sha256 "af6030dc9cb6ccf43f2199116fdbb6b35a13eb1405c1e087ab5b762a8629834f"

      def install
        bin.install "iofogctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.0.6/iofogctl_3.0.6_macos_arm64.tar.gz"
      sha256 "b63f25f35c75e85ba3d13d737a51a9a1935abe7da1f7dfd434f6aaab647641cc"

      def install
        bin.install "iofogctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.0.6/iofogctl_3.0.6_arm64.tar.gz"
      sha256 "3e978eb247bec66cf6c098003edb4e1eeb814f3bcfb42fc27521bc7f35227476"

      def install
        bin.install "iofogctl"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.0.6/iofogctl_3.0.6_amd64.tar.gz"
      sha256 "322f6a8715a40c73cb7bf11c0746073c27cdb339c506e05915d37bf96bc93ae3"

      def install
        bin.install "iofogctl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.0.6/iofogctl_3.0.6_armv6.tar.gz"
      sha256 "5529166fdc9210946a9a3764b9cc8aad4a3864387c684a9e72b4e3c2ec76d8d1"

      def install
        bin.install "iofogctl"
      end
    end
  end

  test do
    system "#{bin}/iofogctl version"
  end
end
