# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iofogctl < Formula
  desc "CLI for ioFog"
  homepage "https://github.com/eclipse-iofog/iofogctl"
  version "3.9.0-rc.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.9.0-rc.4/iofogctl_3.9.0-rc.4_macos_amd64.tar.gz"
      sha256 "17afd222c63c91f10e759f86f66f08ed82b44b88335acbce51ccea19aa77cf78"

      define_method(:install) do
        bin.install "iofogctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.9.0-rc.4/iofogctl_3.9.0-rc.4_macos_arm64.tar.gz"
      sha256 "0298692444f0144d54dcd90a996693cf05d0f8424f0d4a0219821aa4287369fc"

      define_method(:install) do
        bin.install "iofogctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.9.0-rc.4/iofogctl_3.9.0-rc.4_amd64.tar.gz"
      sha256 "d18572db50adadd9eb4f16cc236e1244096d29b3215b06298e8349f20cbc9d3d"
      define_method(:install) do
        bin.install "iofogctl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.9.0-rc.4/iofogctl_3.9.0-rc.4_armv6.tar.gz"
      sha256 "1bbfd82461862e2850c364c2642c62d51ccac1d6b238f418d15ef1e545c12906"
      define_method(:install) do
        bin.install "iofogctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.9.0-rc.4/iofogctl_3.9.0-rc.4_arm64.tar.gz"
      sha256 "acdef8e2047d745994202d26a5c738613decc8980eaf0ffb2a3f5f33c10a6ef9"
      define_method(:install) do
        bin.install "iofogctl"
      end
    end
  end

  test do
    system "#{bin}/iofogctl version"
  end
end
