# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Iofogctl < Formula
  desc "CLI for ioFog"
  homepage "https://github.com/eclipse-iofog/iofogctl"
  version "3.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.8.1/iofogctl_3.8.1_macos_amd64.tar.gz"
      sha256 "261f42b51026d531cf8d1018a0d89ce732baa4b8ad16f6b6ed5981c55f48f0f4"

      define_method(:install) do
        bin.install "iofogctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.8.1/iofogctl_3.8.1_macos_arm64.tar.gz"
      sha256 "8f9305fa180b34e18c02cd1df3448c80bd51553ab1c2dc8dbd4a8b10be15c249"

      define_method(:install) do
        bin.install "iofogctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.8.1/iofogctl_3.8.1_amd64.tar.gz"
      sha256 "fc30439698d1c575ae70595bae31b537d194a223172b6f83f16ac4c97ad9b706"
      define_method(:install) do
        bin.install "iofogctl"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.8.1/iofogctl_3.8.1_armv6.tar.gz"
      sha256 "780005e1810ab0c265206c8c82b9681c78fea1b305550120637c11bf2d2bd496"
      define_method(:install) do
        bin.install "iofogctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eclipse-iofog/iofogctl/releases/download/v3.8.1/iofogctl_3.8.1_arm64.tar.gz"
      sha256 "60797c3cc0cc33e2e42302a97b240a0e5a5ee241c435c7193710afc2663e47a3"
      define_method(:install) do
        bin.install "iofogctl"
      end
    end
  end

  test do
    system "#{bin}/iofogctl version"
  end
end
